#
# ALSO MUST SEE ./docker-compose.override.yml
# the override config is applied automatically by docker-compose
#
version: "3"

volumes:
  # global volume used to share unix sockets
  unixsocks:
    # specify name to avoid default docker-compose prefixing
    name: unixsocks

networks:
  # global network to share between all services (not all services bind to unix sockets right now)
  moonspeaknet:
    # specify name to avoid default docker-compose prefixing
    name: moonspeaknet

services:
  #===================================
  telegram_server_cheker:
    image: "temachpool/moonspeak-telegram_server_cheker:${TAG:-latest}"
    environment:
      MOONSPEAK_TGBOT_TOKEN: "${MOONSPEAK_TGBOT_TOKEN}"
      MOONSPEAK_ADMIN_ID_0: "${MOONSPEAK_ADMIN_ID_0}"
      MOONSPEAK_ADMIN_ID_1: "${MOONSPEAK_ADMIN_ID_1}"
    networks:
      - moonspeaknet
    build:
      context: ./telegram_server_cheker

  gateway:
    image: "temachpool/moonspeak-gateway:${TAG:-latest}"
    volumes:
      - unixsocks:/etc/unixsocks
    networks:
      - moonspeaknet

  router:
    image: "temachpool/moonspeak-router:${TAG:-latest}"
    volumes:
      - unixsocks:/opt/moonspeak/unixsocks
    networks:
      - moonspeaknet
    environment:
      # the router inserts reference to hostname into each feature via <base> tag
      # this supplies the correct name, the field is re-defined in override configs
      MOONSPEAK_DOMAIN: ""
      # turn off debug features
      MOONSPEAK_DEV_MODE: ""
      RUST_LOG: "router=info"

  manager:
    image: "temachpool/moonspeak-manager:${TAG:-latest}"
    volumes:
      - unixsocks:/opt/moonspeak/unixsocks
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - moonspeaknet
    environment:
      MOONSPEAK_UDS: "/opt/moonspeak/unixsocks/manager.sock"
      # the manager writes configuration for graph service which has absolute urls
      # this supplies the correct name, the field is re-defined in override configs
      MOONSPEAK_TLD: ""
      # set debug to off
      PYTHON_ON_WHALES_DEBUG: ""
      LOGLEVEL: "INFO"
      MOONSPEAK_DEVMODE: ""

  #===================================
  # by default do not run grafana and loki, only promtail
  promtail:
    container_name: promtail.moonspeak.localhost
    image: "temachpool/moonspeak-promtail:${TAG:-latest}"
    volumes:
      # hopefully we can get rid of docker sock one day and only parse docker logs
      # for now we just disable promtails HTTP server entry point
      # - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - moonspeaknet
    command: -config.expand-env=true -config.file=/etc/promtail/config.yml -print-config-stderr

  landing:
    image: "temachpool/moonspeak-landing:${TAG:-latest}"
    volumes:
      - unixsocks:/etc/unixsocks
    networks:
      - moonspeaknet

  synonyms:
    image: "temachpool/moonspeak-synonyms:${TAG:-latest}"
    volumes:
      - unixsocks:/opt/moonspeak/unixsocks
    networks:
      - moonspeaknet
    environment:
      GUNICORN_CMD_ARGS: " --bind='0.0.0.0:80' --bind='unix:/opt/moonspeak/unixsocks/synonyms.sock' "

  suggestions:
    image: "temachpool/moonspeak-suggestions:${TAG:-latest}"
    volumes:
      - unixsocks:/opt/moonspeak/unixsocks
    networks:
      - moonspeaknet
    environment:
      MOONSPEAK_HOST: "0.0.0.0"
      MOONSPEAK_PORT: 80

  frequency:
    image: "temachpool/moonspeak-frequency:${TAG:-latest}"
    volumes:
      - unixsocks:/opt/moonspeak/unixsocks
    networks:
      - moonspeaknet
    environment:
      MOONSPEAK_HOST: "0.0.0.0"
      MOONSPEAK_PORT: 80
